---

- name: "SECTION | 4.1| Configure System Accounting (auditd)"
  include: cis_4.1.1.x.yml

- name: "SECTION | 4.1.2.x| Configure Data Retention"
  include: cis_4.1.2.x.yml

- name: "SECTION | 4.2.x| Configure Logging"
  include: cis_4.2.1.x.yml

- name: "SECTION | 4.2.2.x| Configure journald"
  include: cis_4.2.2.x.yml
