---

- name: "AUTOMATED | 1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled"
  block:
  - name: "AUTOMATED | 1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | Edit modprobe config"
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install cramfs(\\s|$)"
      line: "install cramfs /bin/true"
      create: yes
      mode: '0600'

  - name: "AUTOMATED | 1.1.1.1 | PATCH | Remove cramfs module"
    modprobe:
      name: cramfs
      state: absent
  when:
  - rhel7cis_rule_1_1_1_1
  - ansible_connection != 'docker'
  tags:
  - level1
  - AUTOMATED
  - patch
  - rule_1.1.1.1
  - cramfs

- name: "AUTOMATED | 1.1.1.2 | PATCH | Ensure mounting of squashfs filesystems is disabled"
  block:
  - name: "AUTOMATED | 1.1.1.2 | PATCH | Ensure mounting of squashfs filesystems is disabled | Edit modprobe config "
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install squashfs(\\s|$)"
      line: "install squashfs /bin/true"
      create: yes
      mode: '0600'

  - name: "AUTOMATED | 1.1.1.2 | PATCH | Remove squashfs module"
    modprobe:
      name: squashfs
      state: absent
  when:
  - rhel7cis_rule_1_1_1_2
  - ansible_connection != 'docker'
  tags:
  - level1
  - AUTOMATED
  - patch
  - rule_1.1.1.2
  - squashfs

- name: "AUTOMATED | 1.1.1.3 | PATCH | Ensure mounting of udf filesystems is disabled"
  block:
  - name: "AUTOMATED | 1.1.1.3 | PATCH | Ensure mounting of udf filesystems is disabled | Edit modprobe config"
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install udf(\\s|$)"
      line: "install udf /bin/true"
      create: yes
      mode: '0600'
  - name: "AUTOMATED | 1.1.1.3 | PATCH | Remove udf module"
    modprobe:
      name: udf
      state: absent
  when:
  - rhel7cis_rule_1_1_1_3
  - ansible_connection != 'docker'
  tags:
  - level1
  - AUTOMATED
  - patch
  - rule_1.1.1.3
  - udf

- name: "MANUAL| 1.1.1.4 | PATCH | Ensure mounting of FAT filesystems is disabled"
  block:
  - name: "MANUAL | 1.1.1.4 | PATCH | Ensure mounting of FAT filesystems is disabled | Edit modprobe config"
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install vfat(\\s|$)"
      line: "install vfat /bin/true"
      create: yes
      mode: '0600'
  - name: "MANUAL | 1.1.1.4 | PATCH | Remove FAT module"
    modprobe:
      name: vfat
      state: absent
  when:
  - rhel7cis_rule_1_1_1_4
  - ansible_connection != 'docker'
  - rhel7cis_legacy_boot
  tags:
  - level2
  - AUTOMATED
  - patch
  - rule_1.1.1.4
  - vfat
