---

- name: "AUTOMATED | 1.7.1.1 | PATCH | Ensure SELinux is installed"
  package:
    name: libselinux
    state: present
  when:
  - not rhel7cis_selinux_disable
  - rhel7cis_rule_1_7_1_1
  tags:
  - level1
  - AUTOMATED
  - patch
  - rule_1.7.1.1
  vars:
    ansible_python_interpreter: /bin/python

- name: "AUTOMATED | 1.7.1.2 | PATCH | Ensure SELinux is not disabled in bootloader configuration"
  replace:
    dest: /etc/default/grub
    regexp: '(selinux|enforcing)\s*=\s*0\s*'
  register: selinux_grub_patch
  ignore_errors: yes
  notify: grub2cfg
  when:
  - not rhel7cis_selinux_disable
  - rhel7cis_rule_1_7_1_2
  tags:
  - level1
  - AUTOMATED
  - patch
  - rule_1.7.1.2

- name: "AUTOMATED | 1.7.1.3 | PATCH | Ensure SELinux policy is configured\n
         AUTOMATED | 1.7.1.4 | PATCH | Ensure the SELinux state is enforcing or permissive"
  selinux:
    conf: /etc/selinux/config
    policy: "{{ rhel7cis_selinux_pol }}"
    state: "{{ rhel7cis_selinux_state }}"
  when:
  - not rhel7cis_selinux_disable
  - rhel7cis_rule_1_7_1_3
  - rhel7cis_rule_1_7_1_4
  tags:
  - level1
  - AUTOMATED
  - selinux
  - patch
  - rule_1.7.1.3
  - rule_1.7.1.4

- name: "AUTOMATED | 1.7.1.5 | PATCH | Ensure the SELinux state is enforcing"
  selinux:
    conf: /etc/selinux/config
    policy: "{{ rhel7cis_selinux_pol }}"
    state: enforcing
  when:
  - not rhel7cis_selinux_disable
  - not rhel7cis_selinux_state == "permissive"
  - rhel7cis_rule_1_7_1_5
  tags:
  - level2
  - AUTOMATED
  - selinux
  - patch
  - rule_1.7.1.5

- name: "AUTOMATED | 1.7.1.6 | AUDIT | Ensure no unconfined daemons exist"
  block:
  - name: "AUTOMATED | 1.7.1.6 | AUDIT | Ensure no unconfined daemons exist | Find the unconfined daemons"
    shell: ps -eZ | egrep "initrc" | egrep -vw "tr|ps|egrep|bash|awk" | tr ':' ' ' | awk '{ print $NF }'
    register: rhelcis_1_7_1_6_unconf_daemons
    failed_when: no
    changed_when: no

  - name: "AUTOMATED | 1.7.1.6 | AUDIT | Ensure no unconfined daemons exist | Message on no unconfined daemones"
    debug:
      msg: "Good News! There are no unconfined daemons found on your system"
    when: rhelcis_1_7_1_6_unconf_daemons.stdout | length == 0

  - name: "AUTOMATED | 1.7.1.6 | AUDIT | Ensure no unconfined daemons exist | Message on unconfined daemones"
    debug:
      msg: "Warning! You have unconfined daemons: {{ rhelcis_1_7_1_6_unconf_daemons.stdout_lines }}"
    when: rhelcis_1_7_1_6_unconf_daemons.stdout | length > 0
  when:
  - rhel7cis_rule_1_7_1_6
  tags:
  - level1
  - audit
  - rule_1.7.1.6

- name: "AUTOMATED | 1.7.1.7 | PATCH | Ensure SETroubleshoot is not installed"
  package:
    name: setroubleshoot
    state: absent
  when:
  - rhel7cis_rule_1_7_1_7
  tags:
  - level1
  - AUTOMATED
  - selinux
  - patch
  - rule_1.7.1.7
  vars:
    ansible_python_interpreter: /bin/python

- name: "AUTOMATED | 1.7.1.8 | PATCH | Ensure the MCS Translation Service (mcstrans) is not installed"
  package:
    name: mcstrans
    state: absent
  when:
  - rhel7cis_rule_1_7_1_8
  tags:
  - level1
  - AUTOMATED
  - patch
  - rule_1.7.1.8
  vars:
    ansible_python_interpreter: /bin/python
