---

- name: "MANUAL| 1.2.1 | PATCH | Ensure GPG keys are configured"
  block:
  - name: "MANUAL| 1.2.1 | PATCH | Ensure GPG keys are configured | RedHat"
    command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution|lower }}-release
    when:
    - ansible_distribution == "RedHat"

  - name: "MANUAL| 1.2.1 | PATCH | Ensure GPG keys are configured | CentOS"
    command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}
    when:
    - ansible_distribution == "CentOS"

  when:
  - rhel7cis_rule_1_2_1
  tags:
  - level1
  - notAUTOMATED
  - patch
  - rule_1.2.1

- name: "MANUAL| 1.2.2 | Ensure package manager repositories are configured"
  block:
  - name: "MANUAL| 1.2.2 | Ensure package manager repositories are configured"
    command: yum repolist
    changed_when: no
    register: repolist
    tags:
    - skip_ansible_lint

  - name: "AUDIT| 1.2.2 | Ensure package manager repositories are configured"
    debug:
      msg:
      - "Please check against site policy repos listed below match expected:"
      - "{{ repolist.stdout_lines }}"
  when:
  - rhel7cis_rule_1_2_2
  tags:
  - level1
  - notAUTOMATED
  - patch
  - rule_1.2.2
  - skip_ansible_lint

- name: "AUTOMATED | 1.2.3 | PATCH | Ensure gpgcheck is globally activated"
  block:
  - name: "AUTOMATED | 1.2.3 | PATCH | Ensure gpgcheck is globally activated"
    find:
      paths: /etc/yum.repos.d
      patterns: "*.repo"
    register: yum_repos
    changed_when: no

  - name: "AUTOMATED | 1.2.3 | PATCH | Ensure gpgcheck is globally activated"
    replace:
      path: "{{ item.path }}"
      regexp: "^gpgcheck=0"
      replace: "gpgcheck=1"
    loop: "{{ yum_repos.files }}"
  when:
  - rhel7cis_rule_1_2_3
  tags:
  - level1
  - AUTOMATED
  - patch
  - rule_1.2.3


- name: "MANUAL| 1.2.4 | PATCH | Ensure Red Hat Network or Subscription Manager connection is configured"
  command: subscription-manager identity
  changed_when: no
  failed_when: no
  when:
  - ansible_distribution == "RedHat"
  - rhel7cis_rule_1_2_4
  tags:
  - level1
  - notAUTOMATED
  - patch
  - rule_1.2.4
  - skip_ansible_list

- name: "MANUAL | 1.2.5 | PATCH | Disable the rhnsd Daemon"
  service:
    name: rhnsd
    state: stopped
    enabled: no
  when:
  - ansible_distribution == "RedHat" and not rhel7cis_rhnsd_required
  - rhel7cis_rule_1_2_5
  tags:
  - level2
  - patch
  - rule_1.2.5
