---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
