---

- name: "PREREQ | Check required packages installed | Python2"
  package:
    list: "{{ item }}"
    state: present
  loop:
  - rpm-python
  - libselinux-python
  when: ansible_python.version.major == 2
  vars:
    ansible_python_interpreter: "{{ python2_bin }}"

- name: "PREREQ | Add the required packages | Python 3"
  block:
  - name: Check if python36-rpm package installed
    command: rpm -q python36-rpm
    register: python36_rpm_present
    failed_when: ( python36_rpm_present.rc not in [ 0, 1 ] )
    changed_when: false
    args:
      warn: false

  - name: Add the EPEL repository required for the python36-rpm pkg
    package:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present
    register: epel_installed
    when:
    - python36_rpm_present.rc != '0'

  - name: "PREREQ | Check required packages installed | Python3 "
    package:
      name: "{{ item }}"
      state: present
    register: python3reqs_installed
    loop:
    - python36-rpm
    - libselinux-python3

  - name: Disable Epel repo if installed earlier
    command: yum-config-manager disable epel
    when: epel_installed.changed
  when:
  - ( ansible_python.version.major == 3  and ansible_python.version.minor == 6 )
  vars:
    ansible_python_interpreter: "{{ python2_bin }}"
