---

- name: "SCORED | 5.2.1 | PATCH | Ensure permissions on /etc/ssh/sshd_config are configured"
  file:
    dest: /etc/ssh/sshd_config
    state: file
    owner: root
    group: root
    mode: 0600
  when:
  - rhel7cis_rule_5_2_1
  tags:
  - level1
  - patch
  - rule_5.2.1

- name: "SCORED | 5.2.2 | PATCH | Ensure permissions on SSH private host key files are configured"
  block:
  - name: "SCORED | 5.2.2 | AUDIT | Ensure permissions on SSH private host key files are configured"
    find:
      paths:
      - /etc/ssh
      patterns: 'ssh_host_*_key'
      recurse: true
      file_type: any
    register: rhel_07_5_2_2_priv_results

  - name: "SCORED | 5.2.2 | AUDIT | Ensure permissions on SSH private host key files are configured"
    file:
      path: "{{ item.path }}"
      owner: root
      group: root
      mode: 0600
    loop: "{{ rhel_07_5_2_2_priv_results.files }}"
  when:
  - rhel7cis_rule_5_2_2
  tags:
  - level1
  - patch
  - rule_5.2.2

- name: "SCORED | 5.2.3 | PATCH | Ensure permissions on SSH public host key files are configured"
  block:
  - name: "SCORED | 5.2.3 | AUDIT | Ensure permissions on SSH public host key files are configured"
    find:
      paths:
      - /etc/ssh
      patterns: 'ssh_host_*_key'
      recurse: true
      file_type: any
    register: rhel_07_5_2_3_pub_results

  - name: "SCORED | 5.2.3 | AUDIT | Ensure permissions on SSH public host key files are configured"
    file:
      path: "{{ item.path }}"
      owner: root
      group: root
      mode: 0600
    loop: "{{ rhel_07_5_2_3_pub_results.files }}"
  when:
  - rhel7cis_rule_5_2_3
  tags:
  - level1
  - patch
  - rule_5.2.3


- name: "SCORED | 5.2.4 | PATCH | Ensure SSH access is limited"
  block:
  - name: "SCORED | 5.2.4 | PATCH | Ensure SSH access is limited | Add line to sshd_config for allowusers"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^AllowUsers"
      line: AllowUsers {{ rhel7cis_sshd['allowusers'] }}
    notify:
    - restart sshd
    when:
    - "rhel7cis_sshd['allowusers']|default('') | length > 0"

  - name: "SCORED | 5.2.4 | PATCH | Ensure SSH access is limited | Add line to sshd_config for allowgroups"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^AllowGroups"
      line: AllowGroups {{ rhel7cis_sshd['allowgroups'] }}
    notify:
    - restart sshd
    when:
    - "rhel7cis_sshd['allowgroups']|default('') | length > 0"

  - name: "SCORED | 5.2.4 | PATCH | Ensure SSH access is limited | Add line to sshd_config for denyusers"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^DenyUsers"
      line: DenyUsers {{ rhel7cis_sshd['denyusers'] }}
    notify:
    - restart sshd
    when:
    - "rhel7cis_sshd['denyusers']|default('') | length > 0"

  - name: "SCORED | 5.2.4 | PATCH | Ensure SSH access is limited | Add line to sshd_config for denygroups"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^DenyGroups"
      line: DenyGroups {{ rhel7cis_sshd['denygroups'] }}
    notify:
    - restart sshd
    when:
    - "rhel7cis_sshd['denygroups']|default('') | length > 0"
  when:
  - rhel7cis_rule_5_2_4
  tags:
  - level1
  - patch
  - rule_5.2.4


- name: "SCORED | 5.2.5 | PATCH | Ensure SSH LogLevel is appropriate"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#LogLevel|^LogLevel"
    line: 'LogLevel {{ rhel7cis_ssh_loglevel }}'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_5
  tags:
  - level1
  - patch
  - rule_5.2.5

- name: "SCORED | 5.2.6 | PATCH | Ensure SSH X11 forwarding is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#X11Forwarding|^X11Forwarding"
    line: 'X11Forwarding no'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_6
  tags:
  - level1
  - level2
  - patch
  - rule_5.2.6

- name: "SCORED | 5.2.7 | PATCH | Ensure SSH MaxAuthTries is set to 4 or less"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^(#)?MaxAuthTries \d'
    line: 'MaxAuthTries 4'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_7
  tags:
  - level1
  - patch
  - rule_5.2.7

- name: "SCORED | 5.2.8 | PATCH | Ensure SSH IgnoreRhosts is enabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#IgnoreRhosts|^IgnoreRhosts"
    line: 'IgnoreRhosts yes'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_8
  tags:
  - level1
  - patch
  - rule_5.2.8

- name: "SCORED | 5.2.9 | PATCH | Ensure SSH HostbasedAuthentication is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: ^#HostbasedAuthentication|^HostbasedAuthentication"
    line: 'HostbasedAuthentication no'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_9
  tags:
  - level1
  - patch
  - rule_5.2.9

- name: "SCORED | 5.2.10 | PATCH | Ensure SSH root login is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#PermitRootLogin|^PermitRootLogin"
    line: 'PermitRootLogin no'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_10
  tags:
  - level1
  - patch
  - rule_5.2.10

- name: "SCORED | 5.2.11 | PATCH | Ensure SSH PermitEmptyPasswords is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#PermitEmptyPasswords|^PermitEmptyPasswords"
    line: 'PermitEmptyPasswords no'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_11
  tags:
  - level1
  - patch
  - rule_5.2.11

- name: "SCORED | 5.2.12 | PATCH | Ensure SSH PermitUserEnvironment is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#PermitUserEnvironment|^PermitUserEnvironment"
    line: 'PermitUserEnvironment no'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_12
  tags:
  - level1
  - patch
  - rule_5.2.12

- name: "SCORED | 5.2.13 | PATCH | Ensure only strong Ciphers are used"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^Cipherss'
    line: "Ciphers {{ rhel7cis_sshd['ciphers'] }}"
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_13
  tags:
  - level1
  - patch
  - rule_5.2.13

- name: "SCORED | 5.2.14 | PATCH | Ensure only approved MAC algorithms are used"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^MACs'
    line: "MACs {{ rhel7cis_sshd['macs'] }}"
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_14
  tags:
  - level1
  - patch
  - rule_5.2.14

- name: "SCORED | 5.2.15 | PATCH | Ensure only strong Key Exchange algorithms are used"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^KexAlgorithms'
    line: "KexAlgorithms {{ rhel7cis_sshd['kex'] }}"
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_15
  tags:
  - level1
  - patch
  - rule_5.2.15

- name: "SCORED | 5.2.16 | PATCH | Ensure SSH Idle Timeout Interval is configured"
  block:
  - name: "SCORED | 5.2.16 | PATCH | Ensure SSH Idle Timeout Interval is configured | Add line in sshd_config for ClientAliveInterval"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^ClientAliveInterval'
      line: "ClientAliveInterval {{ rhel7cis_sshd['clientaliveinterval'] }}"
    notify:
    - restart sshd

  - name: "SCORED | 5.2.16 | PATCH | Ensure SSH Idle Timeout Interval is configured | Ensure SSH ClientAliveCountMax set to <= 3"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^ClientAliveCountMax'
      line: "ClientAliveCountMax {{ rhel7cis_sshd['clientalivecountmax'] }}"
    notify:
    - restart sshd
  when:
  - rhel7cis_rule_5_2_16
  tags:
  - level1
  - patch
  - rule_5.2.16

- name: "SCORED | 5.2.17 | PATCH | Ensure SSH LoginGraceTime is set to one minute or less"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#LoginGraceTime|^LoginGraceTime"
    line: "LoginGraceTime {{ rhel7cis_sshd['logingracetime'] }}"
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_17
  tags:
  - level1
  - patch
  - rule_5.2.17

- name: "SCORED | 5.2.18 | PATCH | Ensure SSH warning banner is configured"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^Banner'
    line: 'Banner /etc/issue.net'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_18
  tags:
  - level1
  - patch
  - rule_5.2.18

- name: "SCORED | 5.2.19 | PATCH | Ensure SSH PAM is enabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#UsePAM|^UsePAM"
    line: 'UsePAM yes'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_19
  tags:
  - level1
  - patch
  - rule_5.2.16

- name: "SCORED | 5.2.20 | PATCH | Ensure SSH AllowTcpForwarding is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#AllowTcpForwarding|^AllowTcpForwarding"
    line: 'AllowTcpForwarding no'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_20
  tags:
  - level2
  - patch
  - rule_5.2.20

- name: "SCORED | 5.2.21 | PATCH | Ensure SSH MaxStartups is configured"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#MaxStartups|^MaxStartups"
    line: 'MaxStartups 10:30:60'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_21
  tags:
  - level1
  - patch
  - rule_5.2.21

- name: "SCORED | 5.2.22 | PATCH | Ensure SSH MaxSessions is limited"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#MaxSessions|^MaxSessions"
    line: 'MaxSessions {{ rhel7cis_ssh_maxsessions }}'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_2_22
  tags:
  - level1
  - patch
  - rule_5.2.22
